// Traducción de nombres de selecciones (como los devuelven football-data.org
// y api-sports en inglés) al español. Si un nombre no está en el mapa, se
// conserva el original.
const TEAM_NAMES_ES: Record<string, string> = {
  // Anfitriones y América
  'United States': 'Estados Unidos',
  'USA': 'Estados Unidos',
  'Mexico': 'México',
  'Canada': 'Canadá',
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Uruguay': 'Uruguay',
  'Colombia': 'Colombia',
  'Ecuador': 'Ecuador',
  'Peru': 'Perú',
  'Chile': 'Chile',
  'Paraguay': 'Paraguay',
  'Bolivia': 'Bolivia',
  'Venezuela': 'Venezuela',
  'Panama': 'Panamá',
  'Costa Rica': 'Costa Rica',
  'Honduras': 'Honduras',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Jamaica': 'Jamaica',
  'Haiti': 'Haití',
  'Curacao': 'Curazao',
  'Curaçao': 'Curazao',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Suriname': 'Surinam',

  // Europa
  'Spain': 'España',
  'France': 'Francia',
  'Germany': 'Alemania',
  'England': 'Inglaterra',
  'Portugal': 'Portugal',
  'Italy': 'Italia',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Bélgica',
  'Switzerland': 'Suiza',
  'Croatia': 'Croacia',
  'Denmark': 'Dinamarca',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Poland': 'Polonia',
  'Austria': 'Austria',
  'Czech Republic': 'Chequia',
  'Czechia': 'Chequia',
  'Serbia': 'Serbia',
  'Ukraine': 'Ucrania',
  'Turkey': 'Turquía',
  'Türkiye': 'Turquía',
  'Greece': 'Grecia',
  'Scotland': 'Escocia',
  'Wales': 'Gales',
  'Ireland': 'Irlanda',
  'Republic of Ireland': 'Irlanda',
  'Northern Ireland': 'Irlanda del Norte',
  'Hungary': 'Hungría',
  'Romania': 'Rumania',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Albania': 'Albania',
  'North Macedonia': 'Macedonia del Norte',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Finland': 'Finlandia',
  'Iceland': 'Islandia',
  'Russia': 'Rusia',
  'Georgia': 'Georgia',
  'Kosovo': 'Kosovo',

  // África
  'Morocco': 'Marruecos',
  'Senegal': 'Senegal',
  'Ghana': 'Ghana',
  'Nigeria': 'Nigeria',
  'Cameroon': 'Camerún',
  'Egypt': 'Egipto',
  'Algeria': 'Argelia',
  'Tunisia': 'Túnez',
  'Ivory Coast': 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  'South Africa': 'Sudáfrica',
  'Mali': 'Malí',
  'Burkina Faso': 'Burkina Faso',
  'DR Congo': 'RD del Congo',
  'Congo DR': 'RD del Congo',
  'Cape Verde': 'Cabo Verde',
  'Cape Verde Islands': 'Cabo Verde',
  'Zambia': 'Zambia',
  'Gabon': 'Gabón',

  // Asia y Oceanía
  'Japan': 'Japón',
  'South Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'Saudi Arabia': 'Arabia Saudita',
  'Iran': 'Irán',
  'IR Iran': 'Irán',
  'Iraq': 'Irak',
  'Qatar': 'Catar',
  'Australia': 'Australia',
  'New Zealand': 'Nueva Zelanda',
  'Uzbekistan': 'Uzbekistán',
  'Jordan': 'Jordania',
  'United Arab Emirates': 'Emiratos Árabes Unidos',
  'China': 'China',
  'China PR': 'China',
  'Indonesia': 'Indonesia',
  'Thailand': 'Tailandia',
  'Vietnam': 'Vietnam',
  'India': 'India',
  'Oman': 'Omán',
  'Bahrain': 'Baréin',
  'Kuwait': 'Kuwait',
  'Palestine': 'Palestina',
  'Syria': 'Siria',
  'Lebanon': 'Líbano',
  'Kyrgyzstan': 'Kirguistán',
  'Tajikistan': 'Tayikistán'
}

export function translateTeamName(name: string): string {
  return TEAM_NAMES_ES[name] ?? name
}
